### ISSUE TITLE
Does this tool can be used to translate other language to English?

### ISSUE THREAD

**Issue by Ethan-Yami** [MicrosoftTranslator/Text-Translation-API-V3-Java#7]
Hi

    I just want to know this tool whether it can be used to translate other language to English or not ?
    
     I was doing a project that encounter an issue while translate text to English，
     
      Example :
      
      
      curl -X POST "https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=en" \
     -H "Ocp-Apim-Subscription-Key:<Replace Your key>" \
     -H "Ocp-Apim-Subscription-Region:southeastasia" \
     -H "Content-Type: application/json" \
     -d "[{'Text':'您好，很高兴我们能再次相遇。'}]"
     
      Hope you guys will help me to solve this problem.
      
 Thanks.

**Comment by chriswendt1** [comment]
Hi Ethan,
You certainly can translate from other languages to English. You can translate from any language in the list, to any other language in the list. 
The only accepted character encoding for the request is UT-8. Make sure to send your JSON in UTF-8. 
What was the issue you observed?

**Comment by Ethan-Yami** [comment]
Hi Chris,

  I was trying to translate Chinese character to english , But the response is incorrect.  I will put the screenshot below:
  

[This link show the result what I got from transalting Chinese to English ](http://47.102.109.113/Chinese-text.png)
    

   When I use the same code to translate the English to Chinese , The result is fine.
   
 
  [This link show the result from translating English to Chinese](http://47.102.109.113/English-text-Chinese.png)
   

    
  Could you please have a look at it for me? 
     
  Many Thanks

   Ethan Yang.

**Comment by chriswendt1** [comment]
Please use UTF-8 encoding for your input text.

**Comment by Ethan-Yami** [comment]
> 
> 
> Please use UTF-8 encoding for your input text.

Yes, I was using the UTF-8 encoding for my input text. But it's not working...

I was using PHP SDK to test this feature.

**Comment by chriswendt1** [comment]
The request data you show in the picture is \u encoded UTF-16. The API only takes UTF-8 encoding directly, no additional encoding on top of it.
